// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cloud_logic': 'enable',
    'aws_cloud_logic_custom': [{"id":"fb4rsk78nb","name":"CATEGORIESCRUD","description":"","endpoint":"https://fb4rsk78nb.execute-api.eu-west-2.amazonaws.com/Development","region":"eu-west-2","paths":["/CATEGORIES","/CATEGORIES/123"]},{"id":"x7rlz1uprf","name":"PROJECTSCRUD","description":"","endpoint":"https://x7rlz1uprf.execute-api.eu-west-2.amazonaws.com/Development","region":"eu-west-2","paths":["/PROJECTS","/PROJECTS/123"]},{"id":"llp2ky038h","name":"sampleCloudApi","description":"","endpoint":"https://llp2ky038h.execute-api.eu-west-2.amazonaws.com/Development","region":"eu-west-2","paths":["/items","/items/123"]},{"id":"sov3mi07wj","name":"UPLOAD","description":"","endpoint":"https://sov3mi07wj.execute-api.eu-west-2.amazonaws.com/Development","region":"eu-west-2","paths":["/getSignedUrl","/uploads3","/uploads3/123"]}],
    'aws_cognito_identity_pool_id': 'eu-west-2:a30f5bf9-9661-490e-9914-08eb6cd2aee7',
    'aws_cognito_region': 'eu-west-2',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'psbadmin-hosting-mobilehub-962220868',
    'aws_content_delivery_bucket_region': 'eu-west-2',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd1hvvfkf3rlwj1.cloudfront.net',
    'aws_dynamodb': 'enable',
    'aws_dynamodb_all_tables_region': 'eu-west-2',
    'aws_dynamodb_table_schemas': [{"tableName":"psbadmin-mobilehub-962220868-PROJECTS","attributes":[{"name":"ID","type":"N"},{"name":"CATEGORY","type":"S"},{"name":"DESCRIPTION","type":"S"},{"name":"END_DATE","type":"S"},{"name":"LOCATION","type":"S"},{"name":"NAME","type":"S"},{"name":"START_DATE","type":"S"}],"indexes":[],"region":"eu-west-2","hashKey":"ID","rangeKey":"CATEGORY"},{"tableName":"psbadmin-mobilehub-962220868-CATEGORIES","attributes":[{"name":"NAME","type":"S"},{"name":"LOCATION","type":"S"}],"indexes":[],"region":"eu-west-2","hashKey":"NAME"},{"tableName":"psbadmin-mobilehub-962220868-AWSMobileTable","attributes":[{"name":"teamId","type":"S"},{"name":"personId","type":"S"},{"name":"email","type":"S"},{"name":"personName","type":"S"},{"name":"phone","type":"S"}],"indexes":[{"indexName":"personName-index","hashKey":"teamId","rangeKey":"personName"}],"region":"eu-west-2","hashKey":"teamId","rangeKey":"personId"}],
    'aws_mobile_analytics_app_id': 'fdb022fa3a2e4f5fbfff4e0dacfb83d0',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'f270135d-2d8d-11e8-8692-f56c6f73a3e3',
    'aws_project_name': 'psb-admin-2018-03-21-22-00-22',
    'aws_project_region': 'eu-west-2',
    'aws_resource_bucket_name': 'psbadmin-deployments-mobilehub-962220868',
    'aws_resource_name_prefix': 'psbadmin-mobilehub-962220868',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'eu-west-2_hYSog0Fnz',
    'aws_user_pools_mfa_type': 'OFF',
    'aws_user_pools_web_client_id': '5q1mu7e4tgjosrbj06vg69qnh5',
}

export default awsmobile;
